package com.payment.processing.domain.enums;

public enum WebhookEventType {
    PAYMENT_CREATED,
    PAYMENT_AUTHORIZED,
    PAYMENT_CAPTURED,
    PAYMENT_VOIDED,
    REFUND_CREATED,
    FRAUD_HELD,
    FRAUD_APPROVED,
    FRAUD_DECLINED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_UPDATED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_SUSPENDED,
    SUBSCRIPTION_TERMINATED,
    SUBSCRIPTION_EXPIRING,
    UNKNOWN
}

